### PR TITLE
Optimized Firebase

### PR DESCRIPTION
**Pull request by VasPug**
1 hour
Fixed firebase infinite reads. Also renames variables in items in the database and reflected changes in code.

### CODE REVIEW

**Comment by alexbuntaran** [comment]
- functionality works as intended
- follows style guide
- looks good to me

**Review by alexbuntaran — APPROVED** [review]
- functionality works as intended (fixed infinite polling issue)
- follows style guide
- looks good to me

**Review by gartpr — COMMENTED** [review]
Good changes for the renamed items in the database. I needed this info to work on the order tracking page so this is good.

**Review by gartpr — APPROVED** [review]

**Comment by HanYu-Wu04** [comment]
Looks good to me, great job on optimizing firebase.

**Review by HanYu-Wu04 — APPROVED** [review]

**Pull request merged**
