### PR TITLE
Hw issue 25 user information page

### LINKED ISSUE #25: User Information Page

### PR DESCRIPTION
**Pull request by HanYu-Wu04**
## Developer: HanYu Wu

Closes #25

### Pull Request Summary

Fixed existing problem that occur when using google sign in/up, added user information page to allow users to select roles and enter phone number, linked RegisterAndLogin page with UserInformation Page, and linked user information with the backend database.

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Ask for a review in communication channels

### CODE REVIEW

**Review by gartpr — APPROVED** [review]
Looks good to me and follows code standards. The only thing that might need to be changed is some of the comments because a lot of them do not seem very useful.

**Review by VasPug — APPROVED** [review]
Looks good to me. I like how you managed the backend for setting the roles of the user with setDoc.  I also liked the css which makes the page look nice.

**Review by alexbuntaran — APPROVED** [review]
- User Information page looks good and functions properly
- follows style guide
- all looks good to me
- nice work on adding user role selections

**Review by amanikonda123 — APPROVED** [review]
Looks fantastic to me. Like Vasanth said, it was a good decision to organize the styling into its own css file. Everything is consistent with the rest of the codebase and seems to work properly. Good work!

**Pull request merged**
