### PR TITLE
finished contact us page

### PR DESCRIPTION
**Pull request by alexbuntaran**

### CODE REVIEW

**Review by VasPug — APPROVED** [review]
Code is clean and follows coding standards. Looks good to me.

**Review by gartpr — APPROVED** [review]
Follow code guidelines, looks good to me.

**Review by HanYu-Wu04 — APPROVED** [review]
Looks good to me, great job finishing up contact us page.

**Comment by amanikonda123** [comment]
Looks good to me. Great code quality and is consistent with other code.

**Review by amanikonda123 — APPROVED** [review]

**Pull request merged**
