### PR TITLE
finished seller page

### PR DESCRIPTION
**Pull request by amanikonda123**

### CODE REVIEW

**Comment by alexbuntaran** [comment]
- functionality works as intended
- follows style guide
- looks good to me

**Review by VasPug — APPROVED** [review]
Looks good and follows guidelines. Also if you want to get user data you can use context/AuthContext.js to get UID and other user data.

**Review by alexbuntaran — APPROVED** [review]
- functionality works as intended
- follows style guide
- looks good to me

**Comment by HanYu-Wu04** [comment]
Looks good to me, great job finishing up the seller page.

**Review by HanYu-Wu04 — COMMENTED** [review]
Looks good to me

**Review by gartpr — COMMENTED** [review]
Everything looks good here to me. Follows all code guidelines.

**Pull request merged**
