### PR TITLE
Fixes and Delivery Fee

### PR DESCRIPTION
**Pull request by VasPug**
Added checks to make sure the user is signed in before they can order. I also made sure that the user could only order items from one restaurant at a time. Also integrated delivery fee of 20% of the total order.

### CODE REVIEW

**Comment by amanikonda123** [comment]
looks good to me, new changes seem to work properly

**Review by amanikonda123 — APPROVED** [review]

**Review by gartpr — APPROVED** [review]
Everything looks good to me and I like the addition of the delivery fee. It follows the code guidelines.

**Review by alexbuntaran — APPROVED** [review]
- functions as intended
- matches style guide
- all looks good

**Comment by VasPug** [comment]
Took 2 hours

**Pull request merged**
